name: Dependabot Native Trigger

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Log message
        run: |
          echo "GitHub Dependabot version updates are configured natively in .github/dependabot.yml"
